### ISSUE TITLE
SortIndex in the wrong place?

### ISSUE THREAD

**Issue by edsko** [well-typed/ghc-events-analyze#22]
We have this constructor of `EventId`:

``` haskell
    -- | User events
    --
    -- To use user events, do
    --
    -- > traceEventIO "START <label>"
    -- > ...
    -- > traceEventIO "STOP <label>"
  | EventUser String SortIndex
```

This `SortIndex` was introduced in https://github.com/well-typed/ghc-events-analyze/commit/e6bc8360d1084b2e50798d4755f8f265ab27722a (where it was called `GroupId`). However, looking at it now, it seems that the constructor should instead be

``` haskell
  | EventUser SortIndex String
```

so that the `SortIndex` takes priority over the name when sorting events (we sort using the derived `Ord`; see `compareEventIds`, case `SortByName`). @xich , is there a specific reason you added the `SortIndex` (you called it `GroupId`) as the second field?

**Comment by xich** [comment]
I'm not sure I would have named in `SortIndex` (though `GroupId` was also probably a bad name). 

The original intent of that field was really to assign unique ids to events with the same human-readable name. (That is, so the derived `Eq` would do the right thing, but the labels that get printed out don't include the unique id.) I made it the second field exactly so that `Ord` behavior wouldn't change.

For instance:

[(EventUser "foo" 1, EventUser "foo" 3, EventUser "foo" 1, EventUser "foo" 3, EventUser "bar" 2, EventUser "bar" 2)]

Are really three distinct event types "foo1", "foo3", and "bar2" as far as the analysis/grouping is concerned, but the two foos will print with label "foo" and the bar with label "bar". I made this id the second field so if you sorted by name things would come out "bar", "foo", "foo" and not "foo", "bar", "foo".

**Comment by edsko** [comment]
Aha, I see. I misunderstood the purpose. Will update the code and document. Thanks for the quick reply!

**Comment by edsko** [comment]
I've renamed it to `EventSubscript` and documented it in the README at https://github.com/well-typed/ghc-events-analyze#event-subscripts . I guess there is no need for a new release as this didn't actually change the behaviour of the code, only it's documentation. Thanks again!
